server:
  port: "8080"
  host: "0.0.0.0"
  read_timeout: "30s"
  write_timeout: "30s"
  idle_timeout: "60s"

database:
  host: "localhost"
  port: "5432"
  user: "postgres"
  password: "password"
  dbname: "myapp"
  sslmode: "disable"
  max_conns: 10

redis:
  host: "localhost"
  port: "6379"
  password: ""
  db: 0

log:
  level: "info"
  format: "json"
  output_path: ""

jwt:
  secret: "your-super-secret-jwt-key-that-is-at-least-32-characters-long"
  expiration: "24h"
  issuer: "myapp"

email:
  host: "smtp.gmail.com"
  port: 587
  username: "your-email@gmail.com"
  password: "your-app-password"
  from: "noreply@myapp.com"

app:
  name: "My Application"
  environment: "development"
  version: "1.0.0"
  debug: true
