server:
  port: "8080"
  host: "0.0.0.0"
  read_timeout: "30s"
  write_timeout: "30s"
  idle_timeout: "60s"

database:
  # Read/Write Database Configuration (Recommended)
  write_host: "write-db.example.com"
  write_port: "5432"
  write_user: "write_user"
  write_password: "write_password"
  write_dbname: "myapp_write"
  
  read_host: "read-db.example.com"
  read_port: "5432"
  read_user: "read_user"
  read_password: "read_password"
  read_dbname: "myapp_read"
  
  # Legacy Database Configuration (Backward Compatibility)
  host: "localhost"
  port: "5432"
  user: "postgres"
  password: "password"
  dbname: "myapp"
  
  # Database Type and Environment
  sslmode: "disable"
  max_conns: 10
  type: "postgresql"
  environment: "development"
  config_type: "read_write"

redis:
  host: "localhost"
  port: "6379"
  password: ""
  db: 0

log:
  level: "info"
  format: "json"
  output_path: ""

jwt:
  secret: "your-super-secret-jwt-key-that-is-at-least-32-characters-long"
  expiration: "24h"
  issuer: "myapp"

email:
  host: "smtp.gmail.com"
  port: 587
  username: "your-email@gmail.com"
  password: "your-app-password"
  from: "noreply@myapp.com"

app:
  name: "My Application"
  environment: "development"
  version: "1.0.0"
  debug: true
